[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev --optimize-autoloader && npm install && npm run build"

[deploy]
startCommand = "php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && php -S 0.0.0.0:$PORT -t public"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10