name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, bcmath, gd, pdo, pdo_mysql, zip

    - name: Install Composer
      run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

    - name: Reinstall PHP dependencies
      run: composer install --no-dev --optimize-autoloader --prefer-dist

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Reinstall npm dependencies
      run: npm ci

    - name: Build assets
      run: npm run build

    - name: Cache configuration and routes
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

    - name: Trigger Railway Deployment
      env:
        RAILWAY_API_KEY: ${{ secrets.RAILWAY_API_KEY }}
      run: |
        curl -X POST https://backboard.railway.app/v1/projects/937e7253-56bc-42de-9c4c-9fc6f7f53e40/deployments \
          -H "Authorization: Bearer $RAILWAY_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{}'
