name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step to checkout the latest code from the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Step to set up PHP (for Laravel)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' 
          extensions: mbstring, pdo, json, curl, openssl, xml, tokenizer
          coverage: none

      # Step to install Composer dependencies
      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      # Step to set up Node.js
      - name: Use Node 18
        uses: actions/setup-node@v1
        with:
          node-version: 18

      # Step to install Node.js dependencies
      - name: Install Node.js packages
        run: yarn install --frozen-lockfile

      # Step to build assets (if needed)
      - name: Build Assets
        run: yarn build # If you need to build assets like CSS/JS files, adjust this based on your setup

      # Step to install Railway CLI
      - name: Install Railway
        run: npm i -g @railway/cli@latest

      # Step to deploy using Railway CLI
      - name: Deploy to Railway
        run: railway up --service 16441226-53fa-4cd7-ab82-0c8d584d836d --verbose
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
